### PR TITLE
make it work

### PR DESCRIPTION
**Pull request by orefalo**
Hi Ricardo,

I know you are pointing at graphql-ez and it's ecosystem.
yet this plugin can benefit ppl willing to get a small footprint.
Was wondering if you could merge the pull request and republish the npm package

if not, I will create a *2 version

thank you

### CODE REVIEW

**Comment by orefalo** [comment]
Hi Ricardo any updates?

**Comment by orefalo** [comment]
Can you transfer npm package ownership?

**Comment by ricardo-valero** [comment]
yes! I can transfer the ownership, sorry for not responding I never saw the notification until now

**Comment by orefalo** [comment]
Thank you so much for publishing -

**Pull request merged**
